name: pip_services3_rabbitmq
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains RabbitMQ message queues
homepage: https://github.com/pip-services3-dart/pip-services3-rabbitmq-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.4 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_messaging: ">=1.0.0 <2.0.0"
  dart_amqp: ^0.1.4
 
dev_dependencies:
  test: '>=1.14.2 <2.0.0'